name: Build and test pull request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  prebuild:
    uses: ./.github/workflows/build_thirdparty_linux_helper.yml
    with:
      commit_sha: ${{ github.sha }}
    secrets: inherit

  build:
    needs: prebuild
    uses: ./.github/workflows/build_ocean_linux_helper.yml
    with:
      commit_sha: ${{ github.sha }}
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/test_ocean_linux_helper.yml
    with:
      commit_sha: ${{ github.sha }}
