# This workflow builds Ocean on Linux (static)
# Based on : https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build Ocean on Linux (static)

on:
  workflow_run:
    workflows: ["Build Third-party libraries on Linux (static)"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    uses: ./.github/workflows/build_ocean_linux_helper.yml
    with:
      commit_sha: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit
